// export const UPLOAD_USER_AVATAR_REQUEST = 'firebase/UPLOAD_USER_AVATAR_REQUEST';
// export const UPLOAD_USER_AVATAR_SUCCESS = 'firebase/UPLOAD_USER_AVATAR_SUCCESS';
// export const UPLOAD_USER_AVATAR_FAILURE = 'firebase/UPLOAD_USER_AVATAR_FAILURE';
