#!/usr/bin/env node
const getCreator = require('./creators');

const type = process.argv[2];
const fileNames = process.argv[3].split(',');

const create = getCreator(type);

fileNames.forEach(fileName => {
  create(fileName);
});
