export const FETCH_BOOKS_REQUEST = 'books/FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'books/FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'books/FETCH_BOOKS_FAILURE';

export const ADD_COMMENT_REQUEST = 'books/ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'books/ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'books/ADD_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'books/DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'books/DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'books/DELETE_COMMENT_FAILURE';
