export const ADD_COMMENT_REQUEST = 'books/ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'books/ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'books/ADD_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'books/DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'books/DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'books/DELETE_COMMENT_FAILURE';

export const ADD_BOOK_TO_MY_BOOKS_REQUEST = 'books/ADD_BOOK_TO_MY_BOOKS_REQUEST';
export const ADD_BOOK_TO_MY_BOOKS_SUCCESS = 'books/ADD_BOOK_TO_MY_BOOKS_SUCCESS';
export const ADD_BOOK_TO_MY_BOOKS_FAILURE = 'books/ADD_BOOK_TO_MY_BOOKS_FAILURE';

export const DELETE_BOOK_FROM_MY_BOOKS_REQUEST = 'books/DELETE_BOOK_FROM_MY_BOOKS_REQUEST';
export const DELETE_BOOK_FROM_MY_BOOKS_SUCCESS = 'books/DELETE_BOOK_FROM_MY_BOOKS_SUCCESS';
export const DELETE_BOOK_FROM_MY_BOOKS_FAILURE = 'books/DELETE_BOOK_FROM_MY_BOOKS_FAILURE';
