export const ADD_COMMENT_REQUEST = 'firestore/ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'firestore/ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'firestore/ADD_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'firestore/DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'firestore/DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'firestore/DELETE_COMMENT_FAILURE';

export const ADD_BOOK_TO_MY_BOOKS_REQUEST = 'firestore/ADD_BOOK_TO_MY_BOOKS_REQUEST';
export const ADD_BOOK_TO_MY_BOOKS_SUCCESS = 'firestore/ADD_BOOK_TO_MY_BOOKS_SUCCESS';
export const ADD_BOOK_TO_MY_BOOKS_FAILURE = 'firestore/ADD_BOOK_TO_MY_BOOKS_FAILURE';

export const DELETE_BOOK_FROM_MY_BOOKS_REQUEST = 'firestore/DELETE_BOOK_FROM_MY_BOOKS_REQUEST';
export const DELETE_BOOK_FROM_MY_BOOKS_SUCCESS = 'firestore/DELETE_BOOK_FROM_MY_BOOKS_SUCCESS';
export const DELETE_BOOK_FROM_MY_BOOKS_FAILURE = 'firestore/DELETE_BOOK_FROM_MY_BOOKS_FAILURE';

export const SET_BOOK_RATING_REQUEST = 'firestore/SET_BOOK_RATING_REQUEST';
export const SET_BOOK_RATING_SUCCESS = 'firestore/SET_BOOK_RATING_SUCCESS';
export const SET_BOOK_RATING_FAILURE = 'firestore/SET_BOOK_RATING_FAILURE';

export const UPDATE_USER_REQUEST = 'firestore/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'firestore/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'firestore/UPDATE_USER_FAILURE';

export const UPLOAD_USER_AVATAR_REQUEST = 'firestore/UPLOAD_USER_AVATAR_REQUEST';
export const UPLOAD_USER_AVATAR_SUCCESS = 'firestore/UPLOAD_USER_AVATAR_SUCCESS';
export const UPLOAD_USER_AVATAR_FAILURE = 'firestore/UPLOAD_USER_AVATAR_FAILURE';
