export const SHOW_NOTIFICATION = 'app/SHOW_NOTIFICATION';

export const OPEN_SIGN_UP_DIALOG = 'app/OPEN_SIGN_UP_DIALOG';
export const CLOSE_SIGN_UP_DIALOG = 'app/CLOSE_SIGN_UP_DIALOG';

export const OPEN_SIGN_IN_DIALOG = 'app/OPEN_SIGN_IN_DIALOG';
export const CLOSE_SIGN_IN_DIALOG = 'app/CLOSE_SIGN_IN_DIALOG';

export const OPEN_CONFIRM_DIALOG = 'app/OPEN_CONFIRM_DIALOG';
export const CLEAN_CONFIRM_DIALOG = 'app/CLEAN_CONFIRM_DIALOG';
export const CLOSE_CONFIRM_DIALOG = 'app/CLOSE_CONFIRM_DIALOG';
