export const SHOW_NOTIFICATION = 'app/SHOW_NOTIFICATION';

export const OPEN_SIGN_UP_DIALOG = 'app/OPEN_SIGN_UP_DIALOG';
export const CLOSE_SIGN_UP_DIALOG = 'app/CLOSE_SIGN_UP_DIALOG';

export const OPEN_SIGN_IN_DIALOG = 'app/OPEN_SIGN_IN_DIALOG';
export const CLOSE_SIGN_IN_DIALOG = 'app/CLOSE_SIGN_IN_DIALOG';
